name: Update daily_national_estimate Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'backend/daily_national_estimate/**'

jobs:
  update-lambdas:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' 


    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-south-1

    - name: Build average monthly value
      run: |
        python backend/build.py backend/daily_national_estimate

    - name: Update Lambda Function
      run: |
        aws lambda update-function-code \
          --function-name daily_national_estimate \
          --zip-file fileb://backend/daily_national_estimate.zip \
          --publish
